#!/bin/bash
read -p "石头  剪刀  布 "  x
  a="石头剪刀布"
  b=$[RANDOM%3*2]
   p=${a:$b:2}

if    [ $p == 石头 ];then
   if [ $x == 剪刀 ];then
     echo '(电脑)'$p     $x 您输了
    elif [ $x == 布 ];then
     echo '(电脑)'$p     $x 您赢了
    elif [ $x == 石头 ];then
     echo  '(电脑)'$p    $p 平局
    else
     echo "您输入的格式不对"
    fi
elif [ $p == 剪刀 ];then
     if [ $x == 石头 ];then
      echo '(电脑)'$p     $x 您赢了
     elif [ $x == 布 ];then
       echo '(电脑)'$p    $x 您输了
     elif  [ $x == 剪刀 ];then
     echo '(电脑)'$p      $p 平局
     else
     echo  "您输入的格式不对"
     fi
elif  [ $p ==  布 ];then
      if [ $x == 石头 ];then
      echo  '(电脑)'$p    $x 您输了
      elif [ $x ==  剪刀 ];then
      echo  '(电脑)'$p    $x 您赢了
      elif [ $x == 布 ];then
         echo '(电脑)'$p     $p 平局
      else
         echo "请输入的格式不对"
      fi
else
    echo
